try:
    # raise Exception("nabrak")
    ga = 1
except:
    print('nani')